[package]
name = "media-zhihu"
description = "Zhihu support for media-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
clap.workspace = true
hmac = "0.12"
jiff.workspace = true
md-5.workspace = true
media-core.workspace = true
rand.workspace = true
regex.workspace = true
serde_json.workspace = true
tracing.workspace = true
sha1.workspace = true
tokio.workspace = true
url.workspace = true
